### ISSUE TITLE
Up/down arrows do not show up in Chrome and HA iOS app

### ISSUE THREAD

**Issue by brianveltman** [nervetattoo/simple-thermostat#138]
The icons do not show up when viewing in Chrome or iOS app.
Safari works fine. I have not tried FireFox nor Edge.

**Comment by rsperber** [comment]
I have the same issue as you described.. Does seem to work in Edge btw.

Are you maybe using the hassio.local url to access HA? Remove the .local from the url, and see or that works. When I did this the icons returned on one of my devices, though not all, so could just be a coincidence.. Could be because the device is running an older version of Chrome? Maybe this helps for you.

**Comment by loongyh** [comment]
All browsers do not work on my side.

**Comment by gavinwoolley** [comment]
I also see the same issue

**Comment by loongyh** [comment]
Looked around and realised HA [changed the way they load Material Icons since v0.110.0](https://github.com/nervetattoo/simple-thermostat/issues/127#issuecomment-631862145).
Since release 0.35.0 simple-thermostat has updated to follow suit.

Either upgrade your HA to <=v.0.11.0 or downgrade your simple-thermostat to >=0.34.1

 See #127

**Comment by gavinwoolley** [comment]
@loongyh I'm on HA version : 0.112.0 and simple-thermostat : 0.36.0 
Are you saying i need to be on HA lower than 0.111.0 to make it work ?
or should my current combo work?
thanks

**Comment by loongyh** [comment]
@gavinwoolley That's odd, have u tried clearing your browser cache?

**Comment by gavinwoolley** [comment]
> @gavinwoolley That's odd, have u tried clearing your browser cache?

Well..... I just tried Incognito, works perfect, thanks. 👏 

I'd cleared my cache yesterday and spent the whole morning logging into various things again, that i just did not want to go through that pain again today lol

Yes, somebody kick me. 🤦‍♂️ 

Thanks for your help 👍

**Comment by loongyh** [comment]
If you're using Chrome, you can clear the cache just for the specific site by going into dev tools (F12) > Application > Clear Storage > Clear site data
