### ISSUE TITLE
+/- overflow

### ISSUE THREAD

**Issue by Sanderbloem050** [nervetattoo/simple-thermostat#177]
![Screenshot_2020-11-17-06-26-10-70](https://user-images.githubusercontent.com/58403275/99350206-1bb93b00-289e-11eb-8627-f9ae28f696e0.jpg)
Check screenshot for more detail.

**Comment by nervetattoo** [comment]
I've been looking into this and will probably improve it so that the buttons will wrap. However for certain column widths only one button will wrap and it looks like this:

<img width="392" alt="Screenshot 2020-11-17 at 22 20 16" src="https://user-images.githubusercontent.com/45449/99451872-22d65c80-2923-11eb-9036-6dcab207ec6d.png">

I hate that, but having the buttons functional is more important so I will go for this solution. 

If anyone want to improve this further they need to observe the container elements width and calculate if there is enough space for two buttons + current setpoint and either manually wrap both buttons or tune down the font size of the setpoint temperature. (This is as much a note to myself for a possible future)
