### ISSUE TITLE
Display set point temperature as whole number if step size is a whole number

### ISSUE THREAD

**Issue by flyboy013** [nervetattoo/simple-thermostat#30]
When using Fahrenheit temperature scale, temperatures are typically whole numbers and thus displaying the temperature in tenths is unnecessary and uses up space that may be needed elsewhere.  Request that if the step size is a whole number that the set point temperature is also displayed as a whole number. 

Optionally add a card configuration variable to enable/disable the displaying of tenths.

**Comment by flyboy013** [comment]
After giving this some more thought, I think the better way to implement this would be to have a card configuration variable (ie. display_tenths) which would have a default value of true.  My reasoning is that doing it this way would provide backwards compatibility.  If it was implemented based on the step value being a whole number then existing implementations with a whole number step would be effected, which would probably be undesirable.   

So my recommendation would be the card variable for displaying tenths or not.  This would be straight forward configuration wise.

**Comment by nervetattoo** [comment]
I'm quite restrictive on adding options so will have to think through scenarios here.
The only real reason to have the decimal in the first place is because I personally use .5 as step size, which makes sense for celcius. Having a static `.0` if you have 1 as a step size I find hard to phantom ever making sense. If anyone reading this is the person who find that logical, please state so 😛 

I don't care about backwards compatibility until I finally tag the first 1.0 release. This is deliberately on 0.x as I don't consider the card stable enough just yet.

**Comment by flyboy013** [comment]
The only reason that I suggested the card configuration method is that it would provide the user with the utmost control.  They decided if they want the tenths or not.  Using the step size is a round about way in which you're telling the user that if they have a step size of 1 then they just don't get the ".0".  Personally, I'm okay with this, but given the user the control via configuration would be more desirable.  I'm not sure I understand the downside of the additional configuration variable other than the fact that the more configuration options you add, the less "simple" the thermostat becomes. 

I agree that if one specifies a step size of 1 then there probably isn't a good reason to have the tenths, but lets see if someone else chimes in with a good reason for having it.
