### ISSUE TITLE
Unavailable Current Temperature shows as null

### ISSUE THREAD

**Issue by flz** [nervetattoo/simple-thermostat#46]
I have a pool thermostat which sensor is only returning the current temperature if the pump is running. When it isn't, this is what's showing:

<img width="467" alt="Screen Shot 2019-04-06 at 8 57 47 PM" src="https://user-images.githubusercontent.com/48219/55678468-2385c080-58af-11e9-915b-83a9dc15fd63.png">

**Comment by flz** [comment]
How about printing "N/A" instead?

**Comment by nervetattoo** [comment]
Hopefully fixed in https://github.com/nervetattoo/simple-thermostat/releases/tag/0.22.0

**Comment by flz** [comment]
Nope.

<img width="472" alt="Screen Shot 2019-05-16 at 6 26 24 PM" src="https://user-images.githubusercontent.com/48219/57896974-35d90f80-7808-11e9-8581-99d6fe337fe5.png">

**Comment by CarpeDiemRo** [comment]
Hello, I'm using Broadlink to control an old Samsung AC and current temperature appears current_temperature: null. It's seems to be normal as far as my AC doesn't sent temperature data back to HA. My questions are:
1. There is any possibility to integrate Broadlink A1 sensor in order to populate current_temperature: field? 
2. If not, there is any possibility to remove/hide current_temperature: field?  Because it's pretty useless to display no info there.

![Screenshot 2019-06-30 at 10 11 31](https://user-images.githubusercontent.com/38489167/60393582-7ecaf600-9b20-11e9-89c8-37414d2b0946.png)
![Screenshot 2019-06-30 at 10 14 36](https://user-images.githubusercontent.com/38489167/60393583-812d5000-9b20-11e9-9cb8-2f4c6045607c.png)
