### ISSUE TITLE
New Feature Request - Suport for climate group

### ISSUE THREAD

**Issue by soloam** [nervetattoo/simple-thermostat#94]
Hello, in home assistant we can make a group ou climate objects, like several ac's, and control them all at once. If I add this group to the simple thermostat It does not work. Is it possible to support groups?

Thank You

**Comment by nervetattoo** [comment]
To get this straight: You just want to control the group together as one entity? Or do you expect it to show multiple set points as in the more info popover?
Controlling groups as one entity I think should work but I don't think I want to support individual control because then you should just use individual cards in compact mode anyway.
